package uk.ac.nott.cs.g53dia.agent;

enum State {
	ROAMING, MOVING_TO_FUEL, MOVING_TO_STATION, MOVING_TO_WELL, REFUELING, CONSUMING, DISPOSING,
//	SCOUTING, MOVING_TO_FUEL, MOVING_TO_STATION, MOVING_TO_WELL, REFUELING, LOADING_WASTE
}
